algoritmo "areaTrapezio"
// Autor :Victor Hugo
// Data : 13/04/2026
var
//váriaveis
           bMaior, bMenor, h, area: Real

inicio
// Seção de Comandos 
   Escreva("Digite a base maior: ")
   Leia(bMaior)
   
   Escreva("digite a base menor: ")
   Leia(bMenor)
   
   Escreva("Digite a altura: ")
   Leia(h)
   
   area<-((bMaior + bMenor) * h) /2
   
   Escreval("A área do trapézio é: ", area)
fimalgoritmo
