algoritmo "CalculaAreaTerreno"
// Autor : Victor Hugo
// Data : 13/04/2026
var
//Variação
          largura, comprimento, area: Real
          
inicio
// Seção de Comandos
   Escreva("Digite a largura do terreno: ")
   Leia(largura)
   
   Escreva("Digite o comprimento do terreno: ")
   Leia(comprimento)
   
   area<-largura * comprimento
   
   Escreva("A área total do terreno é: ", area)
 
fimalgoritmo
